### ISSUE TITLE
Implication definition not clear

### ISSUE THREAD

**Issue by ghost** [hadipourh/autoguess#5]
Hi I am using your tool to determine a calculation flow. 

my input has some algebraic relations. 

The output I get shows the determination flows in the following format.

X1, X25 in implication relation [X1, X25 => TGOX118] are known: X1, X25 ===> TGOX118

Now I don't understand what this implication relation is? does this mean  TGOX118 = X1*X25?

what about the flow

X13, X21, X29, X37 in implication relation [X13, X21, X29, X37 => TGOX5142231] are known: X13, X21, X29, X37 ===> TGOX5142231?  

also I need only the output file and not the graph. so how to stop the program after generating the output file only?

**Comment by DL2024S108** [comment]
Thanks for your interest in our tool.

Before I answer your question, I want to remind you that my tool only supports algebraic equations over the binary field (i.e., GF(2) = {0, 1}). If your algebraic relations are from a different mathematical space, please be careful when using Autoguess.

Regarding your question about new variables: When the algebraic degree is higher than two (you have multiplications or AND gates), Autoguess creates new variables to linearize these relations. For example, if you have a term like `X1*X25` in your original relations, Autoguess will define a new variable such as `TG0X118 = X1*X25`, and treat this as an additional relation. If the system includes terms with an algebraic degree higher than 2, Autoguess linearizes the system by defining a sequence of new variables and implication relations recursively. For instance, for `W = X*Y*Z`, it first defines a new variable `S = X*Y`, and then another new variable `T = S*Z` to completely simplify the system. 
If you want to see the intermediate system of equations that Autoguess creates you can activate the log by using `--log 1` switch within your command. 

Additionally, depending on whether you turn on preprocessing by using `--preprocess 1`, Autoguess may apply a Gaussian-elimination process to the original system of equations (again, I emphasize, over GF(2)) to pull out new relations/information from the original equations. Therefore, when you use Autoguess with a system of multivariate algebraic equations (over GF(2)), you may see several new variables in the determination flow.

About your question on turning off the figure generator: I know it can be time-consuming sometimes. So, you can turn off the figure generator by using `--tikz 0`.

Please let me know if this does not fully answer your question or if you have any more questions.
By the way, feel free to report any issues you find with Autoguess or let me know if you have any comments. It helps me improve the tool.

**Comment by hadipourh** [comment]
Thanks for your interest in our tool.

Before I answer your question, I want to remind you that my tool only supports algebraic equations over the binary field (i.e., GF(2) = {0, 1}). If your algebraic relations are from a different mathematical space, please be careful when using Autoguess.

Regarding your question about new variables: When the algebraic degree is higher than two (you have multiplications or AND gates), Autoguess creates new variables to linearize these relations. For example, if you have a term like `X1*X25` in your original relations, Autoguess will define a new variable such as `TG0X118 = X1*X25`, and treat this as an additional relation. If the system includes terms with an algebraic degree higher than 2, Autoguess linearizes the system by defining a sequence of new variables and implication relations recursively. For instance, for `W = X*Y*Z`, it first defines a new variable `S = X*Y`, and then another new variable `T = S*Z` to linearize the system. I used [DegreeDropper](https://github.com/hadipourh/DegreeDropper), which I developed during my undergraduate studies, for this purpose. 
If you want to see the intermediate system of equations that Autoguess creates from the original one, you can activate the log by using `--log 1` switch within your command.

Additionally, depending on whether you turn on preprocessing by using `--preprocess 1`, Autoguess may apply a Gaussian-elimination process to the original system of equations (again, I emphasize, over GF(2)) to pull out new relations/information from the original equations. Therefore, when you use Autoguess with a system of multivariate algebraic equations (over GF(2)), you may see several new variables in the determination flow.

About your question on turning off the figure generator: I know it can be time-consuming sometimes. So, you can turn off the figure generator by using `--tikz 0`.

Please let me know if this does not fully answer your question or if you have any more questions.
By the way, feel free to report any issues you find with Autoguess or let me know if you have any comments. It helps me improve the tool.

**Comment by ghost** [comment]
Thank you for replying so clearly. I understand it now. I hope you don't mind If I modify your code (with citations) to adapt to my settings.

**Comment by hadipourh** [comment]
I will be happy if you find our tool useful. 
If you believe your modifications could benefit other users, please feel free to send a pull request and contribute to the tool.
